### ISSUE TITLE
2st AquaFish.ico

### ISSUE THREAD

**Issue by fuggla** [owlnical/fc-aqua-fish#6]
@JontePonte vi har två identiska ico-filer:

- /AquaFish.ico
- /assets/images/AquaFish.ico

Vet vi varför? Kan vi ta bort en?

**Comment by JontePonte** [comment]
Vi får kalla tillbaka alla sålda kopior...

**Comment by fuggla** [comment]
It's done, har gått ut med en press release (och ändrad elite i a02e35fc753d7921682eb19f5abbfec6f04b2ff9)
